services:
  - type: web
    name: globaltit-site
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn globaltit_site.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        sync: false